### ISSUE TITLE
Add Support For `role: service`

### ISSUE THREAD

**Issue by si-c613** [newrelic/newrelic-prometheus-configurator#370]
### Description
Prometheus supports Kubernetes service discovery for more roles than just Pod and Endpoint.
We have a use case for some applications which all report the same metric so we only want to scrape the Service rather than each Endpoint or Pod.

### Acceptance Criteria
Add support for `service: true` to be set inside the `kubernetes` discovery config.

Helm values:
```
config:
  kubernetes:
    jobs:
      - job_name_prefix: default
        target_discovery:
          service: true # <---- new config value
          filter:
            annotations:
              prometheus.io/scrape-service: true
```

Prometheus config:
```
  kubernetes_sd_configs:
  - role: service
    kubeconfig_file: ""
    follow_redirects: true
    enable_http2: true
```

### Describe Alternatives
Configure `static_targets`

### Dependencies
documentation will need updating

### Additional context
NA

### Estimates
S = 1-3 days

## For Maintainers Only or Hero Triaging this bug
*Suggested Priority (P1,P2,P3,P4,P5):*
*Suggested T-Shirt size (S, M, L, XL, Unknown):*
