### ISSUE TITLE
Add job proxy_url to configurator spec

### ISSUE THREAD

**Issue by carlossscastro** [newrelic/newrelic-prometheus-configurator#56]
We will need to add `proxy_url` support on the configurator to allow mocked tests on K8s envs.
Currently `proxy_url` is not added when executing  `runConfigurator`:

```
common:
  scrape_interval: 1s
kubernetes:
  jobs:
    - job_name_prefix: test-k8s
      proxy_url: %s
      target_discovery:
        pod: true
```

Once this is implemented we should improve test with a mocked metrics instead of `scrape_duration_seconds`
https://github.com/newrelic/newrelic-prometheus-configurator/blob/main/test/integration/integration_kubernetes_test.go#L73
