### ISSUE TITLE
Add drop feature to k8s `filters`

### ISSUE THREAD

**Issue by gsanchezgavier** [newrelic/newrelic-prometheus-configurator#78]
Currently `filter` only supports inclusion rules, meaning that targets matching the filters will be included.

This makes hard to implement some use cases when same common labels are shared for targets but there are a few that applies for on group. With the current filter capabilities the solution ends up either having totally separate set of annotations/labels for the different targets groups , or scraping some of the targets in different jobs.

For example if we want to add a special label to targets that needs a special `scrape_interval` or any other special configuration like Authorization, proxy, etc. a new job will be added filtering those targets if all are annotated with `prometheus.io/scrape: "true"`

``` yaml
common:
  scrape_interval: 30s
kubernetes:
  jobs:
    - job_name_prefix: default-targets
      target_discovery: 
        pod: true
        filter:
          annotation:
            prometheus.io/scrape: "true"

    - job_name_prefix: slow-targets
      scrape_interval: 60s
      target_discovery: 
        pod: true
        filter:
          annotation:
            prometheus.io/scrape: "true"
          label:
            slow-scrape: "true"
```

As possible solutions:
- We could add exclusion rules to the filter , so labels/annotations defined `drops` the matching targets. The example could look like this:
``` yaml
common:
  scrape_interval: 30s
kubernetes:
  jobs:
    - job_name_prefix: default-targets
      target_discovery: 
        pod: true
        filter:
          annotation:
            prometheus.io/scrape: "true"
          label-drop:
            slow-scrape: "true"

    - job_name_prefix: slow-targets
      scrape_interval: 60s
      target_discovery: 
        pod: true
        filter:
          annotation:
            prometheus.io/scrape: "true"
          label:
            slow-scrape: "true"
```
